CREATE TABLE "public"."posts" (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text UNIQUE NOT NULL,
    body text NOT NULL,
    author_id bigint references "public"."users"(id),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT current_timestamp
);
CREATE INDEX on "public"."posts" (author_id);

COMMENT ON TABLE "public"."posts" is '文章';
COMMENT ON COLUMN "public"."posts"."id" IS 'id';
COMMENT ON COLUMN "public"."posts"."title" IS '标题';
COMMENT ON COLUMN "public"."posts"."body" IS '正文';
